[app]
platformio_cmd = platformio
cubemx_cmd = /root/STM32CubeMX/STM32CubeMX
java_cmd = None

[project]
cubemx_script_content = config load ${ioc_file_absolute_path}
	generate code ${project_dir_absolute_path}
	exit
platformio_ini_patch_content = [platformio]
	include_dir = Inc
	src_dir = Src
board = stm32f303k8
ioc_file = TS_mainboard.ioc
cleanup_ignore = TS_mainboard.ioc
cleanup_use_git = False
inspect_ioc = True
last_error = FileNotFoundError: [Errno 2] No such file or directory: '/root/STM32CubeMX/STM32CubeMX'
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.10/dist-packages/stm32pio/cli/app.py", line 198, in main
	    project.generate_code()
	  File "/usr/local/lib/python3.10/dist-packages/stm32pio/core/project.py", line 129, in generate_code
	    return self.cubemx.generate_code(script_template=self.config.get('project', 'cubemx_script_content'))
	  File "/usr/local/lib/python3.10/dist-packages/stm32pio/core/cubemx.py", line 201, in generate_code
	    completed_process, std_output = self.execute_script(cubemx_script_content)
	  File "/usr/local/lib/python3.10/dist-packages/stm32pio/core/cubemx.py", line 180, in execute_script
	    raise e  # re-raise an exception after the 'finally' block
	  File "/usr/local/lib/python3.10/dist-packages/stm32pio/core/cubemx.py", line 176, in execute_script
	    completed_process = subprocess.run(command_arr, stdout=log.pipe, stderr=log.pipe)
	  File "/usr/lib/python3.10/subprocess.py", line 501, in run
	    with Popen(*popenargs, **kwargs) as process:
	  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
	    self._execute_child(args, executable, preexec_fn, close_fds,
	  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
	    raise child_exception_type(errno_num, err_msg, err_filename)

